// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function reducer(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return state - 1 | 0;
    } else {
      return state + 1 | 0;
    }
  } else {
    return action._0;
  }
}

function useCounterReducer(initVal) {
  var match = React.useReducer(reducer, initVal);
  var dispatch = match[1];
  var increment = function (_event) {
    return Curry._1(dispatch, /* Increment */0);
  };
  var decrement = function (_event) {
    return Curry._1(dispatch, /* Decrement */1);
  };
  var reset = function (_event) {
    return Curry._1(dispatch, /* Reset */{
                _0: initVal
              });
  };
  return [
          match[0],
          increment,
          decrement,
          reset
        ];
}

export {
  reducer ,
  useCounterReducer ,
  
}
/* react Not a pure module */
