// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var text = Props.text;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: "btn",
              onClick: onClick
            }, text);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
