// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Button$ReactResTest from "./components/button.bs.js";
import * as UseCounterReducer$ReactResTest from "./hooks/useCounterReducer.bs.js";

import './index.css';
;

function Index$App(Props) {
  var match = UseCounterReducer$ReactResTest.useCounterReducer(0);
  var reset = match[3];
  var decrement = match[2];
  var increment = match[1];
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h1", undefined, "Counter App"), React.createElement("h1", {
                  className: "value"
                }, String(match[0])), React.createElement(Button$ReactResTest.make, {
                  text: "Increment",
                  onClick: (function (_e) {
                      return Curry._1(increment, undefined);
                    })
                }), React.createElement(Button$ReactResTest.make, {
                  text: "Decrement",
                  onClick: (function (_e) {
                      return Curry._1(decrement, undefined);
                    })
                }), React.createElement(Button$ReactResTest.make, {
                  text: "Reset",
                  onClick: (function (_e) {
                      return Curry._1(reset, undefined);
                    })
                }));
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Index$App, {}), root);
}

export {
  App ,
  
}
/*  Not a pure module */
